<a href="https://colab.research.google.com/github/sagarkakkar03/Data-science/blob/main/assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv('AusApparalSales4thQrt2020.csv')

In [3]:
df.head()

         Date        Time State     Group  Unit  Sales
0  1-Oct-2020     Morning    WA      Kids     8  20000
1  1-Oct-2020     Morning    WA       Men     8  20000
2  1-Oct-2020     Morning    WA     Women     4  10000
3  1-Oct-2020     Morning    WA   Seniors    15  37500
4  1-Oct-2020   Afternoon    WA      Kids     3   7500

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7560 entries, 0 to 7559
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    7560 non-null   object
 1   Time    7560 non-null   object
 2   State   7560 non-null   object
 3   Group   7560 non-null   object
 4   Unit    7560 non-null   int64
 5   Sales   7560 non-null   int64
dtypes: int64(2), object(4)
memory usage: 354.5+ KB

In [5]:
df.describe()

              Unit          Sales
count  7560.000000    7560.000000
mean     18.005423   45013.558201
std      12.901403   32253.506944
min       2.000000    5000.000000
25%       8.000000   20000.000000
50%      14.000000   35000.000000
75%      26.000000   65000.000000
max      65.000000  162500.000000

In [6]:
df['Time'].unique()

array([' Morning', ' Afternoon', ' Evening'], dtype=object)

In [7]:
df['Date'].unique()

array(['1-Oct-2020', '2-Oct-2020', '3-Oct-2020', '4-Oct-2020',
       '5-Oct-2020', '6-Oct-2020', '7-Oct-2020', '8-Oct-2020',
       '9-Oct-2020', '10-Oct-2020', '11-Oct-2020', '12-Oct-2020',
       '13-Oct-2020', '14-Oct-2020', '15-Oct-2020', '16-Oct-2020',
       '17-Oct-2020', '18-Oct-2020', '19-Oct-2020', '20-Oct-2020',
       '21-Oct-2020', '22-Oct-2020', '23-Oct-2020', '24-Oct-2020',
       '25-Oct-2020', '26-Oct-2020', '27-Oct-2020', '28-Oct-2020',
       '29-Oct-2020', '30-Oct-2020', '1-Nov-2020', '2-Nov-2020',
       '3-Nov-2020', '4-Nov-2020', '5-Nov-2020', '6-Nov-2020',
       '7-Nov-2020', '8-Nov-2020', '9-Nov-2020', '10-Nov-2020',
       '11-Nov-2020', '12-Nov-2020', '13-Nov-2020', '14-Nov-2020',
       '15-Nov-2020', '16-Nov-2020', '17-Nov-2020', '18-Nov-2020',
       '19-Nov-2020', '20-Nov-2020', '21-Nov-2020', '22-Nov-2020',
       '23-Nov-2020', '24-Nov-2020', '25-Nov-2020', '26-Nov-2020',
       '27-Nov-2020', '28-Nov-2020', '29-Nov-2020', '30-Nov-2020',
       '1-Dec-2020', '2-Dec-2020', '3-Dec-2020', '4-Dec-2020',
       '5-Dec-2020', '6-Dec-2020', '7-Dec-2020', '8-Dec-2020',
       '9-Dec-2020', '10-Dec-2020', '11-Dec-2020', '12-Dec-2020',
       '13-Dec-2020', '14-Dec-2020', '15-Dec-2020', '16-Dec-2020',
       '17-Dec-2020', '18-Dec-2020', '19-Dec-2020', '20-Dec-2020',
       '21-Dec-2020', '22-Dec-2020', '23-Dec-2020', '24-Dec-2020',
       '25-Dec-2020', '26-Dec-2020', '27-Dec-2020', '28-Dec-2020',
       '29-Dec-2020', '30-Dec-2020'], dtype=object)

In [8]:
df['State'].unique()

array([' WA', ' NT', ' SA', ' VIC', ' QLD', ' NSW', ' TAS'], dtype=object)

In [9]:
df['Group'].unique()

array([' Kids', ' Men', ' Women', ' Seniors'], dtype=object)

There are no missing values

In [12]:
df.drop_duplicates()

             Date        Time State     Group  Unit  Sales
0      1-Oct-2020     Morning    WA      Kids     8  20000
1      1-Oct-2020     Morning    WA       Men     8  20000
2      1-Oct-2020     Morning    WA     Women     4  10000
3      1-Oct-2020     Morning    WA   Seniors    15  37500
4      1-Oct-2020   Afternoon    WA      Kids     3   7500
...           ...         ...   ...       ...   ...    ...
7555  30-Dec-2020   Afternoon   TAS   Seniors    14  35000
7556  30-Dec-2020     Evening   TAS      Kids    15  37500
7557  30-Dec-2020     Evening   TAS       Men    15  37500
7558  30-Dec-2020     Evening   TAS     Women    11  27500
7559  30-Dec-2020     Evening   TAS   Seniors    13  32500

[7560 rows x 6 columns]

Sales by State

In [26]:
from matplotlib import pyplot as plt
import plotly.express as px

In [30]:
df_state = df.groupby('State')['Sales'].sum().reset_index()
df_state

  State      Sales
0   NSW   74970000
1    NT   22580000
2   QLD   33417500
3    SA   58857500
4   TAS   22760000
5   VIC  105565000
6    WA   22152500

In [31]:
px.pie(df_state, names='State', values='Sales')

Highest sales is in **VIC**

Lowest sales is in **WA**

In [32]:
df_state = df.groupby('Group')['Sales'].sum().reset_index()
df_state

      Group     Sales
0      Kids  85072500
1       Men  85750000
2   Seniors  84037500
3     Women  85442500

In [33]:
px.pie(df_state, names='Group', values='Sales')

In [37]:
df.groupby(['Group', 'State'])['Sales'].sum().unstack(fill_value=0)

State         NSW       NT      QLD        SA      TAS       VIC       WA
Group
Kids     18587500  5700000  8510000  14515000  5775000  26360000  5625000
Men      19022500  5762500  8392500  14655000  5757500  26407500  5752500
Seniors  18187500  5465000  8190000  14717500  5650000  26315000  5512500
Women    19172500  5652500  8325000  14970000  5577500  26482500  5262500

In [18]:
df['Date'] = pd.to_datetime(df['Date'], format='%d-%b-%Y')

In [38]:
df['week'] = df['Date'].dt.isocalendar().week.astype(int)
df['month'] = df['Date'].dt.month.astype(int)

## Weekly Report

In [46]:
df.groupby('week').agg(
    total_sales = ('Sales', 'sum'),
    total_units = ('Unit', 'sum'),
    avg_sales = ('Sales', 'mean'),
    avg_units = ('Unit', 'mean')
).reset_index()

    week  total_sales  total_units     avg_sales  avg_units
0     40     15045000         6018  44776.785714  17.910714
1     41     27002500        10801  45922.619048  18.369048
2     42     26640000        10656  45306.122449  18.122449
3     43     26815000        10726  45603.741497  18.241497
4     44     21807500         8723  43268.849206  17.307540
5     45     20865000         8346  35484.693878  14.193878
6     46     21172500         8469  36007.653061  14.403061
7     47     21112500         8445  35905.612245  14.362245
8     48     21477500         8591  36526.360544  14.610544
9     49     29622500        11849  50378.401361  20.151361
10    50     31525000        12610  53613.945578  21.445578
11    51     31655000        12662  53835.034014  21.534014
12    52     31770000        12708  54030.612245  21.612245
13    53     13792500         5517  54732.142857  21.892857

Monthly Report

In [47]:
df.groupby('month').agg(
    total_sales = ('Sales', 'sum'),
    total_units = ('Unit', 'sum'),
    avg_sales = ('Sales', 'mean'),
    avg_units = ('Unit', 'mean')
).reset_index()

   month  total_sales  total_units     avg_sales  avg_units
0     10    114290000        45716  45353.174603  18.141270
1     11     90682500        36273  35985.119048  14.394048
2     12    135330000        54132  53702.380952  21.480952

# Quaterly report

In [48]:
df['Quarter'] = df['Date'].dt.to_period('Q')

In [50]:
df.groupby('Quarter').agg(
    total_sales = ('Sales', 'sum'),
    total_units = ('Unit', 'sum'),
    avg_sales = ('Sales', 'mean'),
    avg_units = ('Unit', 'mean')
).reset_index()

  Quarter  total_sales  total_units     avg_sales  avg_units
0  2020Q4    340302500       136121  45013.558201  18.005423

In [56]:
df2 = df.groupby(['State', 'Group'], as_index=False)['Sales'].sum()
fig = px.bar(df2, x="State", y="Sales", color="Group")
fig.update_layout(title="Sales by State and Group")
fig.show()