<a href="https://colab.research.google.com/github/sagarkakkar03/Data-science/blob/main/CategoricalDataHandlingTechnques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('preprocessExample.csv')
data

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8      NaN  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
data['Country'].fillna(data['Country'].mode()[0], inplace = True)
data

/tmp/ipython-input-2986427700.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Country'].fillna(data['Country'].mode()[0], inplace = True)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8   France  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
data['Age'].fillna(data['Age'].median(), inplace = True)
data['Salary'].fillna(data['Salary'].mean(), inplace = True)
data

/tmp/ipython-input-1306500449.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Age'].fillna(data['Age'].median(), inplace = True)
/tmp/ipython-input-1306500449.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Salary'].fillna(data['Salary'].mean(), inplace = True)

   Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes
5   France  35.0  58000.000000       Yes
6    Spain  38.0  52000.000000        No
7   France  48.0  79000.000000       Yes
8   France  50.0  83000.000000        No
9   France  37.0  67000.000000       Yes

In [6]:
pd.get_dummies(data['Country'], dtype=int)

   France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
4       0        1      0
5       1        0      0
6       0        0      1
7       1        0      0
8       1        0      0
9       1        0      0

In [9]:
finalDataset = pd.concat([pd.get_dummies(data['Country'], dtype=int), data.iloc[:, [1,2,3]]], axis = 1)
finalDataset

   France  Germany  Spain   Age        Salary Purchased
0       1        0      0  44.0  72000.000000        No
1       0        0      1  27.0  48000.000000       Yes
2       0        1      0  30.0  54000.000000        No
3       0        0      1  38.0  61000.000000        No
4       0        1      0  40.0  63777.777778       Yes
5       1        0      0  35.0  58000.000000       Yes
6       0        0      1  38.0  52000.000000        No
7       1        0      0  48.0  79000.000000       Yes
8       1        0      0  50.0  83000.000000        No
9       1        0      0  37.0  67000.000000       Yes

In [14]:
freq = data['Country'].value_counts(normalize = True)

In [17]:
data['freq'] = data['Country'].map(freq)
data

   Country   Age        Salary Purchased  freq
0   France  44.0  72000.000000        No   0.5
1    Spain  27.0  48000.000000       Yes   0.3
2  Germany  30.0  54000.000000        No   0.2
3    Spain  38.0  61000.000000        No   0.3
4  Germany  40.0  63777.777778       Yes   0.2
5   France  35.0  58000.000000       Yes   0.5
6    Spain  38.0  52000.000000        No   0.3
7   France  48.0  79000.000000       Yes   0.5
8   France  50.0  83000.000000        No   0.5
9   France  37.0  67000.000000       Yes   0.5