<a href="https://colab.research.google.com/github/sagarkakkar03/Data-science/blob/main/data_cleaning_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('datasetExample.csv')

In [ ]:
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+
5,6,35+,3,Ibys,Non-Veg,1909,2,122220,35+
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122,35+
7,8,20-25,7,LemonTree,Veg,2999,-10,345673,20-25
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
9,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
10,10,30-35,5,RedFox,non-Veg,-6755,4,87777,30-35

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       11 non-null     int64
 1   Age_Group        11 non-null     object
 2   Rating(1-5)      11 non-null     int64
 3   Hotel            11 non-null     object
 4   FoodPreference   11 non-null     object
 5   Bill             11 non-null     int64
 6   NoOfPax          11 non-null     int64
 7   EstimatedSalary  11 non-null     int64
 8   Age_Group.1      11 non-null     object
dtypes: int64(5), object(4)
memory usage: 924.0+ bytes

In [5]:
df.drop_duplicates(inplace=True, ignore_index=True)

In [ ]:
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+
5,6,35+,3,Ibys,Non-Veg,1909,2,122220,35+
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122,35+
7,8,20-25,7,LemonTree,Veg,2999,-10,345673,20-25
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
9,10,30-35,5,RedFox,non-Veg,-6755,4,87777,30-35

In [6]:
df[df['Age_Group'] != df['Age_Group.1']]

Empty DataFrame
Columns: [CustomerID, Age_Group, Rating(1-5), Hotel, FoodPreference, Bill, NoOfPax, EstimatedSalary, Age_Group.1]
Index: []

In [7]:
df.drop(columns = ['Age_Group.1'], inplace=True)

In [ ]:
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4,Ibis,veg,1300,2,40000
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000
2,3,25-30,6,RedFox,Veg,1322,2,30000
3,4,20-25,-1,LemonTree,Veg,1234,2,120000
4,5,35+,3,Ibis,Vegetarian,989,2,45000
5,6,35+,3,Ibys,Non-Veg,1909,2,122220
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122
7,8,20-25,7,LemonTree,Veg,2999,-10,345673
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999
9,10,30-35,5,RedFox,non-Veg,-6755,4,87777

In [8]:
df['Bill'].loc[df['Bill'] < 0] = np.nan

/tmp/ipython-input-2292340053.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Bill'].loc[df['Bill'] < 0] = np.nan
/tmp/ipython-input-2292340053.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Bill'].loc[df['Bill'] < 0] = np.nan

In [ ]:
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4,Ibis,veg,1300.0,2,40000
1,2,30-35,5,LemonTree,Non-Veg,2000.0,3,59000
2,3,25-30,6,RedFox,Veg,1322.0,2,30000
3,4,20-25,-1,LemonTree,Veg,1234.0,2,120000
4,5,35+,3,Ibis,Vegetarian,989.0,2,45000
5,6,35+,3,Ibys,Non-Veg,1909.0,2,122220
6,7,35+,4,RedFox,Vegetarian,1000.0,-1,21122
7,8,20-25,7,LemonTree,Veg,2999.0,-10,345673
8,9,25-30,2,Ibis,Non-Veg,3456.0,3,-99999
9,10,30-35,5,RedFox,non-Veg,NaN,4,87777

In [9]:
df['Rating(1-5)'].loc[(df['Rating(1-5)'] >= 6) | (df['Rating(1-5)'] <= 0)] = np.nan

/tmp/ipython-input-557606451.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Rating(1-5)'].loc[(df['Rating(1-5)'] >= 6) | (df['Rating(1-5)'] <= 0)] = np.nan
/tmp/ipython-input-557606451.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Rating(1-5)'].loc[(df['Rating(1-5)'] >= 6) | (df['Rating(1-5)'] <= 0)] = np.nan

In [ ]:
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4.0,Ibis,veg,1300.0,2,40000
1,2,30-35,5.0,LemonTree,Non-Veg,2000.0,3,59000
2,3,25-30,NaN,RedFox,Veg,1322.0,2,30000
3,4,20-25,NaN,LemonTree,Veg,1234.0,2,120000
4,5,35+,3.0,Ibis,Vegetarian,989.0,2,45000
5,6,35+,3.0,Ibys,Non-Veg,1909.0,2,122220
6,7,35+,4.0,RedFox,Vegetarian,1000.0,-1,21122
7,8,20-25,NaN,LemonTree,Veg,2999.0,-10,345673
8,9,25-30,2.0,Ibis,Non-Veg,3456.0,3,-99999
9,10,30-35,5.0,RedFox,non-Veg,NaN,4,87777

In [10]:
df['EstimatedSalary'].loc[df['EstimatedSalary'] <= 0] = np.nan

/tmp/ipython-input-950278609.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['EstimatedSalary'].loc[df['EstimatedSalary'] <= 0] = np.nan
/tmp/ipython-input-950278609.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['EstimatedSalary'].loc[df['EstimatedSalary'] <= 0] = np.nan

In [ ]:
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4.0,Ibis,veg,1300.0,2,40000.0
1,2,30-35,5.0,LemonTree,Non-Veg,2000.0,3,59000.0
2,3,25-30,NaN,RedFox,Veg,1322.0,2,30000.0
3,4,20-25,NaN,LemonTree,Veg,1234.0,2,120000.0
4,5,35+,3.0,Ibis,Vegetarian,989.0,2,45000.0
5,6,35+,3.0,Ibys,Non-Veg,1909.0,2,122220.0
6,7,35+,4.0,RedFox,Vegetarian,1000.0,-1,21122.0
7,8,20-25,NaN,LemonTree,Veg,2999.0,-10,345673.0
8,9,25-30,2.0,Ibis,Non-Veg,3456.0,3,NaN
9,10,30-35,5.0,RedFox,non-Veg,NaN,4,87777.0

In [11]:
df['NoOfPax'].loc[df['NoOfPax'] < 0] = np.nan

/tmp/ipython-input-3965454687.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['NoOfPax'].loc[df['NoOfPax'] < 0] = np.nan
/tmp/ipython-input-3965454687.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['NoOfPax'].loc[df['NoOfPax'] < 0] = np.nan

In [12]:
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4.0,Ibis,veg,1300.0,2.0,40000.0
1,2,30-35,5.0,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3,25-30,NaN,RedFox,Veg,1322.0,2.0,30000.0
3,4,20-25,NaN,LemonTree,Veg,1234.0,2.0,120000.0
4,5,35+,3.0,Ibis,Vegetarian,989.0,2.0,45000.0
5,6,35+,3.0,Ibys,Non-Veg,1909.0,2.0,122220.0
6,7,35+,4.0,RedFox,Vegetarian,1000.0,NaN,21122.0
7,8,20-25,NaN,LemonTree,Veg,2999.0,NaN,345673.0
8,9,25-30,2.0,Ibis,Non-Veg,3456.0,3.0,NaN
9,10,30-35,5.0,RedFox,non-Veg,NaN,4.0,87777.0

In [14]:
df['Hotel'].unique()

array(['Ibis', 'LemonTree', 'RedFox', 'Ibys'], dtype=object)

In [16]:
df['Hotel'].replace('Ibys', 'ibis', inplace=True)

/tmp/ipython-input-231373737.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Hotel'].replace('Ibys', 'ibis', inplace=True)

In [17]:
df

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4.0,Ibis,veg,1300.0,2.0,40000.0
1,2,30-35,5.0,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3,25-30,NaN,RedFox,Veg,1322.0,2.0,30000.0
3,4,20-25,NaN,LemonTree,Veg,1234.0,2.0,120000.0
4,5,35+,3.0,Ibis,Vegetarian,989.0,2.0,45000.0
5,6,35+,3.0,ibis,Non-Veg,1909.0,2.0,122220.0
6,7,35+,4.0,RedFox,Vegetarian,1000.0,NaN,21122.0
7,8,20-25,NaN,LemonTree,Veg,2999.0,NaN,345673.0
8,9,25-30,2.0,Ibis,Non-Veg,3456.0,3.0,NaN
9,10,30-35,5.0,RedFox,non-Veg,NaN,4.0,87777.0

In [24]:
df['Hotel'] = df['Hotel'].apply(str.lower)

In [25]:
df['FoodPreference'].replace('Vegetarian', 'veg', inplace=True)
df['FoodPreference'] = df['FoodPreference'].apply(str.lower)
df

/tmp/ipython-input-1225309390.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['FoodPreference'].replace('Vegetarian', 'veg', inplace=True)

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4.0,ibis,veg,1300.0,2.0,40000.0
1,2,30-35,5.0,lemontree,non-veg,2000.0,3.0,59000.0
2,3,25-30,NaN,redfox,veg,1322.0,2.0,30000.0
3,4,20-25,NaN,lemontree,veg,1234.0,2.0,120000.0
4,5,35+,3.0,ibis,veg,989.0,2.0,45000.0
5,6,35+,3.0,ibis,non-veg,1909.0,2.0,122220.0
6,7,35+,4.0,redfox,veg,1000.0,NaN,21122.0
7,8,20-25,NaN,lemontree,veg,2999.0,NaN,345673.0
8,9,25-30,2.0,ibis,non-veg,3456.0,3.0,NaN
9,10,30-35,5.0,redfox,non-veg,NaN,4.0,87777.0